### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by zc994646659** [Chengcheng-Xiao/VASP_LOL#1]
Dear Dr. Xiao,

I hope this email finds you well. I am writing to inquire about a potential bug in the spin-polarized ELF calculations generated by VASP 5.4.4. Moreover, I would like to know if there are any known bugs related to the  COHP (Crystal Orbital Hamilton Population).

As a researcher working with VASP, it is essential for us to ensure the accuracy and reliability of our calculations. Therefore, I would greatly appreciate any insights or information you can provide on these matters. If there are any known bugs or issues, it would be very useful to understand the nature of these problems and any potential workarounds.

Thank you very much for your time and attention to this matter. I look forward to your response.

Best regards,
zhouchao

**Comment by Chengcheng-Xiao** [comment]
To answer your first question: Yes, the known bug for spin-polarized ELF exists in VASP v5.4.4. For VASP v6.3. it can be fixed using [`VASP6.3_ELF.patch`](https://github.com/Chengcheng-Xiao/VASP_LOL/blob/master/VASP6.3_ELF.patch), I'd imagine adapting it to v5.4.4 to be trivial. 

As for your second question: I am not aware of any bugs in COHP (presumably you are talking about the [Lobster code](http://www.cohp.de)?) as I'm not a part of its dev group.

**Comment by Chengcheng-Xiao** [comment]
Closed for now.
